# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dbc398cf7cb6acde1e2a5d563cf4606f016ff88a50dcb2ca2923c023140a59528e754c2414f72aab4d39c232ccbda784a378a8ae3c63521d65e7d0769391258

test:
  secret_key_base: ef7a637fcae5aa2fd9fa1853e0918e152a72d9f366bff3c467a37628dcc579086344315a10b1b44c4a8d800bec4ca19098342a583456fafb284ed4aa75f63c27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
